#!/usr/bin/python
# -*- coding: utf-8 -*-

# execution.py

from __future__ import print_function

from abc import ABCMeta, abstractmethod
import datetime
try:
    import Queue as queue
except ImportError:
    import queue

from event import FillEvent, OrderEvent
import time
import krakenex
from pykrakenapi import KrakenAPI



class ExecutionHandler(object):
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market. 

    The handlers can be used to subclass simulated brokerages
    or live brokerages, with identical interfaces. This allows
    strategies to be backtested in a very similar manner to the
    live trading engine.
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def execute_order(self, event):
        """
        Takes an Order event and executes it, producing
        a Fill event that gets placed onto the Events queue.

        Parameters:
        event - Contains an Event object with order information.
        """
        raise NotImplementedError("Should implement execute_order()")


class SimulatedExecutionHandler(ExecutionHandler):
    """
    The simulated execution handler simply converts all order
    objects into their equivalent fill objects automatically
    without latency, slippage or fill-ratio issues.

    This allows a straightforward "first go" test of any strategy,
    before implementation with a more sophisticated execution
    handler.
    """
    
    def __init__(self, events):
        """
        Initialises the handler, setting the event queues
        up internally.

        Parameters:
        events - The Queue of Event objects.
        """
        self.events = events

    def execute_order(self, event):
        """
        Simply converts Order objects into Fill objects naively,
        i.e. without any latency, slippage or fill ratio problems.

        Parameters:
        event - Contains an Event object with order information.
        """
        if event.type == 'ORDER':
            fill_event = FillEvent(
                datetime.datetime.utcnow(), event.symbol,
                'test', event.quantity, event.direction, None
            )
            self.events.put(fill_event)
            

class KrakenExecutionHandler(ExecutionHandler):
    """
    Handles order execution via Kraken
    API, for use against accounts when trading live
    directly. 
    """
    with open('/home/alex/Documents/skola/finproj/key.txt') as f:
             key = f.read()
    with open('/home/alex/Documents/skola/finproj/secret.txt') as f:
        secret = f.read()
        
    api = krakenex.API(key.rstrip(), secret.rstrip())
    connection = KrakenAPI(api)
    
    def __init__(
        self, events,connection, currency="ZEUR",validate=True
        ):
        """
        Initialises the IBExecutionHandler instance.
        """
        with open('/home/alex/Documents/skola/finproj/key.txt') as f:
               key = f.read()
        with open('/home/alex/Documents/skola/finproj/secret.txt') as f:
            secret = f.read()
        
        api = krakenex.API(key.rstrip(), secret.rstrip())
        self.connection = KrakenAPI(api)
        
        
        self.validate=validate
        self.events = events
        self.currency = currency
        self.validate=validate
        
    def execute_order(self, event,val):
        """
        Creates the necessary InteractiveBrokers order object
        and submits it to IB via their API.
        The results are then queried in order to generate a
        corresponding Fill object, which is placed back on
        the event queue.
        Parameters:
        event - Contains an Event object with order information.
        """
        
        # OrderEvent(symbol, order_type, abs(cur_quantity), 'BUY')
        if event.type == 'ORDER':
        # Prepare the parameters for the asset order
            pair = event.symbol
            ordertype = event.order_type.lower()
            if ordertype=='mkt':
                ordertype='market'
            volume = event.quantity
            type = event.direction.lower()
            print(pair,ordertype,volume,type)
            orderinfo=self.connection.add_standard_order(pair,type,ordertype,volume)
            # orderinfo=connection.add_standard_order(pair,,type,ordertype,volume,validate)
            # orderdescription=orderinfo['descr']['order']
            if val==False:
                orderID=orderinfo['txid']
                trade_info=self.connection.get_trades_history()[0].iloc[orderID]
                # ['OU47U4-SDQUW-QFZ7ND']
                trade_info=trade_info[trade_info['ordertxid'] == orderID]
                
                fill_event = FillEvent(
                trade_info.name, pair,
                'kraken', trade_info['cost'], type, trade_info['fee']
                )
            
            else:    
                fill_event = FillEvent(timeindex=
                datetime.datetime.utcnow(), symbol=pair,
                exchange='test',quantity=event.quantity, fill_cost=1, direction=type, commission=None
                )
          
            self.events.put(fill_event)